#page title
page_title                                : TeleTux Telegram Android Client                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://github.com/TeleTux/TeleTux/releases                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Telegram's unofficial client, which is free and open source and respects your privacy .

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Freetux                                
your_link                                 : https://freetux.ir                     
your_city                                 : freeland                                
email_address                             : itsfreetux@gmail.com
facebook_username                         :                                           
instagram_username                        : freetux01
twitter_username                          : itsfreetux
github_username                           : herotux
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Jalali calendar, Jalali datepicker and schedulepicker
    description                           : #Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Unlimited login accounts
    description                           : #Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : sign-in-alt
    
  - title                                 : Built-in VMess, Shadowsocks, SSR, Trojan-GFW proxies support
    description                           : #Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Built-in public proxy list / Proxy subscription support
    description                           : #Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Ipv6 MTProxy support
    description                           : #Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : fa-server

  - title                                 : Scan the QR code (any link, can add a proxy)
    description                           : #Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : qrcode
  
  - title                                 : Translation support for selected text on input and in messages
    description                           : #Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : translate

  - title                                 : Delete all messages in group
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : trash-alt

  - title                                 : Proxies, groups, channels, sticker packs are able to shared as QR codes
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : qrcode

  - title                                 : Telegram X style menu for unpinning messages
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Built-in Material Design themes / Telegram X style icons
    description                           : # New Feature Description
    fontawesome_icon_name                 : icons

  - title                                 : Custom app ID and Hash (optional TeleTux / Android / Android X or Manual input)
    description                           : # New Feature Description
    fontawesome_icon_name                 : mobile-alt



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown